apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecsdemo-frontend-ingress
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: ecsdemo-frontend-lb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/subnets: ${PUBLIC_SUBNET_IDS}
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/certificate-arn: ${ACM_CERT_ARN}
    # alb.ingress.kubernetes.io/security-groups: ${SECURITY_GROUP_FOR_ALB}
    alb.ingress.kubernetes.io/healthcheck-port: "3000"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ecsdemo-frontend
              port:
                number: 80
